algo: maddpg

actor_lr: 1.0e-3
critic_lr: 1.0e-3
gamma: 0.99
tau: 0.01
exploration_noise: 0.1

hidden_sizes: [64, 64]

update_every: 1
gradient_steps: 1
learning_starts: 1000
batch_size: 256
buffer_size: 250000
