algo: "masac"

actor_lr: 3.0e-4
critic_lr: 3.0e-4
alpha_lr: 3.0e-4
gamma: 0.99
tau: 0.01

autotune_alpha: true
alpha_init: 0.2
gumbel_tau: 1.0 # Temperature for Gumbel-Softmax

hidden_sizes: [64, 64]

update_every: 1
gradient_steps: 1
learning_starts: 1000
batch_size: 256
buffer_size: 250000
